# Configuration for Recorder

NORMALIZATION_FACTOR: 3
SAMPLE_RATE: 44100
AUDIO_CHANNELS: 2
BUFFER_SIZE: 1024
MAX_SILENCE_LENGTH: 2 # in seconds
SILENCE_THRESHOLD: 25
AUDIO_FORMAT: pyaudio.paInt16
OUTPUT_DIRECTORY: path/to/your/output/directory
